import { NextResponse } from 'next/server';
const crypto = require('crypto');
const prisma = require('../../../../lib/prisma');

// Verifies a signed, expiring magic-link token instead of a raw PIN in the
// URL. The signature proves the link was generated by us (using
// MAGIC_LINK_SECRET) and hasn't been tampered with; the expiry means an old
// or leaked link stops working on its own. The real PIN is never present
// in the link at any point, unlike the old ?code=X&pin=Y scheme.
export async function POST(req) {
  try {
    const { shop, exp, sig } = await req.json();

    if (!shop || !exp || !sig) {
      return NextResponse.json({ error: 'Invalid link' }, { status: 400 });
    }

    const secret = process.env.MAGIC_LINK_SECRET;
    if (!secret) {
      console.error('MAGIC_LINK_SECRET is not set in .env');
      return NextResponse.json({ error: 'Shop login links are not configured yet' }, { status: 503 });
    }

    const expiryMs = Number(exp) * 1000;
    if (!Number.isFinite(expiryMs) || Date.now() > expiryMs) {
      return NextResponse.json({ error: 'This link has expired. Ask for a new one.' }, { status: 401 });
    }

    const expected = crypto
      .createHmac('sha256', secret)
      .update(`${shop}.${exp}`)
      .digest('hex');

    const sigBuf = Buffer.from(sig, 'hex');
    const expectedBuf = Buffer.from(expected, 'hex');

    const valid =
      sigBuf.length === expectedBuf.length && crypto.timingSafeEqual(sigBuf, expectedBuf);

    if (!valid) {
      return NextResponse.json({ error: 'This link is invalid.' }, { status: 401 });
    }

    const foundShop = await prisma.fairPriceShop.findUnique({
      where: { loginCode: shop.trim().toUpperCase() },
    });

    if (!foundShop) {
      return NextResponse.json({ error: 'Shop not found' }, { status: 404 });
    }

    // Same shape as /api/shops/auth's success response, so the dashboard
    // (which just reads this from localStorage) works identically no
    // matter which login path was used.
    return NextResponse.json({ id: foundShop.id, name: foundShop.name, address: foundShop.address });
  } catch (err) {
    console.error('auth-token error:', err);
    return NextResponse.json({ error: 'Login failed' }, { status: 500 });
  }
}